### ISSUE TITLE
Interfacing   RFID Reader And LED

### ISSUE THREAD

**Issue by mikeshams** [chandrashekar1994/captson-project-summer-2020#5]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connecting the RFID to the BBB in terms of Hardware and Software and what's the possible solution?

**Comment by chandrashekar1994** [comment]
1. Rfid tag uses SPI protocol specifically because if you use UART and I2C  protocol in which sensors are already grounded so it's difficult to interface between BBB and RFID.
2. If you need to interface between BBB and RFID you have to mask the ports of BBB that is difficult because input and output sensors of RFID  may not show the actual performance.
3. So that is why we induced Aurdino uno to make an intermediate between BBB and RFID
