### ISSUE TITLE
Interfacing Thingspeak with Beaglebone Black Wireless

### ISSUE THREAD

**Issue by mikeshams** [chandrashekar1994/captson-project-summer-2020#8]

**Comment by mikeshams** [comment]
1. what issues did you or others might face when interfacing the BBB with ThingSpeak?
2. How did you resolve them?

**Comment by Darshanmistry1995** [comment]
1. issue which I have faced during interfacing thingSpeak is that the header file was missing in the C code because the C code does not have the sstream library to give a support the header file to main program.

2. So I have found the after the next comment of the namespace we have same declaration  like "namespace exploringBB"
    and the C++ code has the library support of sstream and by which I can push numeric data using a stringstream head .
so by using C++ code I have solved the issue.
