### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by mikeshams** [chandrashekar1994/captson-project-summer-2020#9]

**Comment by mikeshams** [comment]
1. what limitations do you have if there is no library for the components when creating the PCB layout?
2. how to show the physical components on the PCB via EASY EDA?

**Comment by Darshanmistry1995** [comment]
1. Some of the components does not contain library directly on the software ,but we have a features like "user contribution" we can take help but still some of them have does not contain footprint and because of that it can not be shown on physical view .

2. After completing a routing process we can see a physical view of the PCB via 3D view option in EasyEDA designing tool, But make sure we have to provide a components values in the schematic diagram so that it will shown the clear and detail view of the physical components.
